update

diff --git a/cdrip b/cdrip
--- a/cdrip
+++ b/cdrip
@@ -80,8 +80,45 @@ checkdep "${force:=false}"
 
 getdev
 
-printf 'Closing CD tray (if open)...\n'
-eject -t "$dev"
+#ckdevout="$(setcd -i "$dev")"
+#ec1="$?"
+#[[ "$ckdevout" = *\ is\ open ]] && printf 'Closing CD tray...\n' && { ejectout="$(eject -t "$dev" &> )"; ec2="$?"; }
+#if [[ "$ckdevout" = Can\''t open device: No such file or directory' ]]; then error...
+#((ec1|ec2)) && if [[ "$ejectout" = 'eject: CD-ROM tray close command failed: No such file or directory' ]]; then
+#    printf '[%s%sWARN%s] eject reported CD-ROM tray close command failed\nContinuing...' "$bold" "$yellow" "$tput0"
+#  elif [[ "$ejectout" = 'eject: '*': not found mountpoint or device with the given name: command not found' ]]; then
+#    printf '[%s%sERROR%s] eject did not recognize the CD-ROM device "%s".\nThis likely means that it does not exist and this script will fail.\nCheck the device and try again. (exit 1)' "$bold" "$red" "$tput0"
+#    exit 1
+#  else
+#    printf '[%s%sWARN%s] eject reported an error:\n%s\n Attempting to continue...' "$bold" "$yellow" "$tput0"
+#  fi
+
+ckdevout="$(setcd -i "$dev")"
+ec1="$?"
+
+if [[ "$ckdevout" = *"is open"* ]]; then
+  printf 'Closing CD tray...\n'
+  ejectout="$(eject -t "$dev" 2>&1)"
+  ec2="$?"
+elif [[ "$ckdevout" = "Can't open device: No such file or directory" || ! -e "$dev" ]]; then
+  printf '[%s%sERROR%s] Device "%s" not found.\nCheck the device path and try again.\n' \
+    "$bold" "$red" "$tput0" "$dev"
+  exit 1
+fi
+
+if (( ec1 || ec2 )); then
+  if [[ "$ejectout" = 'eject: CD-ROM tray close command failed: No such file or directory' ]]; then
+    printf '[%s%sWARN%s] eject reported CD-ROM tray close command failed.\nContinuing...\n' \
+      "$bold" "$yellow" "$tput0"
+  elif [[ "$ejectout" = 'eject: '*': not found mountpoint or device with the given name: command not found' ]]; then
+    printf '[%s%sERROR%s] eject did not recognize the CD-ROM device "%s".\nThis likely means it does not exist.\nCheck the device and try again. (exit 1)\n' \
+      "$bold" "$red" "$tput0" "$dev"
+    exit 1
+  else
+    printf '[%s%sWARN%s] eject/setcd reported an unexpected error:\n%s\n%s\nAttempting to continue...\n' \
+      "$bold" "$yellow" "$tput0" "$ckdevout" "$ejectout"
+  fi
+fi
 
 printf '\nChecking for CD ...\n'
 
