update

diff --git a/cdrip b/cdrip
--- a/cdrip
+++ b/cdrip
@@ -51,11 +51,23 @@ checkdep(){
  exit 1
 }
 
+helpout(){
+  getdev
+  printf 'Usage: %s -y -d <device> <album name>' "${0##*/}"
+  printf '-y to force yes to all prompts\n'
+  printf '-d <device> to specify a different device than %s' "$dev"
+  printf '-h|--help to display this help message and exit'
+  exit 0
+}
+
 #[[ "$1" = @(edit|e|-e) ]] && editscript
 
-[[ "$1" = -y ]] && force=true && shift
-
-[[ "$1" = -d ]] && dev="$2" && shift 2
+while (( $# > 0 )); do
+  [[ "$1" = -y ]] && force=true && shift
+  [[ "$1" = -d ]] && dev="$2" && shift 2
+  [[ "$1" =~ -h|--help ]] && helpout && exit 1
+  [[ "$@" ]] && name="$@" && shift "$#"
+done
 
 if [[ ! -d "$ripdir" ]]; then
   mkdir -p "$ripdir"
@@ -77,23 +89,23 @@ cdcheck
 cdparanoia -Q -d "$dev"
 
 tracks="$(cd-discid $dev)"; tracks="${tracks#* }"; tracks="${tracks%% *}"
-printf \\n\\n
-[[ "$1" ]] && name="$1" || read -p "File name?  " name
-#echo "There are $tracks tracks.  The files will be named "$name"-{01.."$tracks"}.flac in "$ripdir""$name""
-printf '\nThere are %s tracks.  The files will be named "%s-{01..%s}.flac" in "%s%s"' "$tracks" "$name" "$tracks" "$ripdir" "$name"
+printf \\n
+[[ "$name" ]] || read -p "File name? " name
 
-optputdir="$ripdir/$name"
-mkdirout="$(mkdir "$ripdir$name" 2>&1)"
+outputdir="$ripdir/$name"
+mkdirout="$(mkdir "$outputdir" 2>&1)"
 ec="$?"
 
 if (( ec )); then
-  printf '\n[%sERROR%s] mkdir %s%s resulted in non-zero exit code:\n%s: %s(exit 1)' "$red$bold" "$tput0" "$ec" "$mkdirout"
+  printf '\n[%s%sERROR%s] mkdir %s%s resulted in non-zero exit code:\n%s: %s(exit 1)' "$red" "$bold" "$tput0" "$ec" "$mkdirout"
   exit 1
 else
-  printf '\n%s%sDirectory %s/%s created%s' "$bold" "$yellow" "$ripdir" "$name" "$tput0"
+  printf '\n%s%sDirectory %s created%s' "$bold" "$yellow" "$outputdir" "$name" "$tput0"
 fi
 
-cd "$ripdir$name"
+printf '\nThere are %s tracks.\nThe files will be named "%s-{01..%s}.flac" in "%s"' "$tracks" "$name" "$tracks" "$outputdir"
+
+cd "$outputdir"
 printf \\nPWD\:\ %s\\n\\n "$PWD"
 ls -alF
 printf \\n\\n
